### PR TITLE
Support for latest ipmitool and update_flash in petitboot

### PR DESCRIPTION
**Pull request by hegdevasant**
Please pull below two patches 

https://github.com/hegdevasant/buildroot/commit/add65ba428317bb038eba3c897fe934e91062c42 https://github.com/hegdevasant/buildroot/commit/d6e121c3fc22470b17ff3e5a74f8c8e1373b47f4

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/buildroot/17)

### CODE REVIEW

**Comment by shenki** [comment]
Hey @hegdevasant , just to confirm you're after these two upstream commits?

https://github.com/buildroot/buildroot/commit/cfe151b724956535f3a60f96410850676f3cdc0b

https://github.com/buildroot/buildroot/commit/6142906c9755b2613df0b92f60ead59e41527716

I have cherry picked them in.

**Comment by shenki** [comment]
These will be pulled into op-build with https://github.com/open-power/op-build/pull/422

**Comment by hegdevasant** [comment]
Joel,

Yes. They are in upstream. I've mentioned upstream commit ID's as well.


-Vasant

**Comment by hegdevasant** [comment]
Joel,

Looks like you have not pulled patches from fw-update branch.

-Vasant

**Comment by shenki** [comment]
That is correct. We have moved to buildroot 2016.05 for op-build, and the two patches are included in that release.

```
$ git tag --contains cfe151b
2016.05
$ git branch  --contains cfe151b
  2016.05-op-build
* master
$ git tag   --contains 6142906
2016.05
$ git branch  --contains 6142906
  2016.05-op-build
* master
```

**Comment by hegdevasant** [comment]
Joel,
Ah! I just looked into master.. I see required patches in other branch. Thanks!

-Vasant

**Pull request closed without merging**
