### PR TITLE
Fix fedora32 build

### PR DESCRIPTION
**Pull request by stewartsmith**
Fix building op-build on Fedora 32.

Mostly backports from newer buildroot.

### CODE REVIEW

**Comment by klauskiwi** [comment]
looks good to me, and FWIW, I tested it with the latest op-build on fedora32 container using witherspoon,garrison,zz,palmetto defconfigs and everything seems fine

**Comment by klauskiwi** [comment]
@shenki Joel any comments?

**Comment by shenki** [comment]
The changes look good. I am not sure how to do a normal fast forward merge with the github UI so I will merge these in and push the branch using the command line.

**Comment by shenki** [comment]
Thanks for the patches @stewartsmith. These are merged to the 2019.05-op-build branch as of 4a064c9005c800a115a81cc8be0627a35a5954d6.

**Comment by shenki** [comment]
Bump is here: https://github.com/open-power/op-build/pull/3693

**Pull request closed without merging**
